# Generated by Django 2.1.5 on 2019-02-09 06:50

from django.db import migrations, models
import shop.helper


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20190209_0837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='random_order_id',
            field=models.IntegerField(default=shop.helper.random_int, unique=True),
        ),
        migrations.AlterField(
            model_name='payment_log',
            name='payment_code',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
