# Generated by Django 2.1.5 on 2019-01-31 03:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20190131_0646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='parentCategory',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.Category'),
        ),
    ]
