# Generated by Django 2.1.5 on 2019-02-25 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_auto_20190216_0619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='pic',
            field=models.ImageField(default='upload/images/no-img.jpg', upload_to='upload/product/images'),
        ),
        migrations.AlterField(
            model_name='shop_user',
            name='profile_pic',
            field=models.ImageField(default='upload/images/no-img.jpg', upload_to='upload/profile/images'),
        ),
    ]
