# Generated by Django 2.1.5 on 2019-01-31 03:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_image_gallery_tag'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='image_gallery',
            options={'verbose_name': 'Image Gallery', 'verbose_name_plural': 'Image Gallery'},
        ),
    ]
