# Generated by Django 2.1.5 on 2019-01-31 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_auto_20190131_0727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image_gallery',
            name='pic',
            field=models.ImageField(default='media/upload/images/no-img.jpg', upload_to='media/upload/images'),
        ),
    ]
