# Generated by Django 2.1.5 on 2019-02-01 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_auto_20190131_0730'),
    ]

    operations = [
        migrations.AddField(
            model_name='image_gallery',
            name='alt',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='image_gallery',
            name='description',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
