# Generated by Django 2.1.5 on 2019-03-12 03:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_order_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shop_user',
            name='city',
        ),
        migrations.RemoveField(
            model_name='shop_user',
            name='user',
        ),
        migrations.DeleteModel(
            name='Shop_user',
        ),
    ]
