# Generated by Django 2.1.5 on 2019-02-02 03:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_auto_20190202_0631'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shop_user',
            options={'verbose_name': 'Shop User', 'verbose_name_plural': 'Shop User'},
        ),
        migrations.AddField(
            model_name='shop_user',
            name='city',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.City'),
        ),
    ]
