# Generated by Django 2.1.5 on 2019-02-03 03:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import shop.Enums


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shop', '0013_auto_20190202_0634'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nik_name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('content', models.TextField(max_length=1000)),
                ('publish_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[(shop.Enums.Order_state('Draft'), 'Draft'), (shop.Enums.Order_state('Published'), 'Published'), (shop.Enums.Order_state('Reopen'), 'Reopen')], max_length=50)),
                ('tags', models.ManyToManyField(null=True, to='shop.Tag')),
                ('writer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='shop_user',
            name='city',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.City'),
        ),
    ]
