# Generated by Django 2.1.5 on 2019-03-15 03:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_auto_20190313_0713'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='random_order_id',
        ),
    ]
