# Generated by Django 2.1.5 on 2019-03-15 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_remove_order_random_order_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='count_of_allow_download',
            field=models.IntegerField(blank=True, default=10),
        ),
        migrations.AlterField(
            model_name='order',
            name='date_of_expire_download',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_type',
            field=models.IntegerField(blank=True, choices=[(1, 'At place'), (2, 'Online')], default=2, null=True),
        ),
    ]
