# Generated by Django 2.1.5 on 2019-02-03 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0015_auto_20190203_0656'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='nik_name',
            new_name='title',
        ),
        migrations.AlterField(
            model_name='product',
            name='tags',
            field=models.ManyToManyField(null=True, to='shop.Tag'),
        ),
    ]
